// Complete list of cultural institutions participating in Culturele INTROWEEK MBO 2026
// Based on the official program schedule

export interface CulturalInstitution {
  id: string
  name: string
  address: string
  district: string
  description: string
  capacity: number
  availableDays: string[]
  timeSlots: { day: string; time: string; capacity: number }[]
  sense: "Zien" | "Horen" | "Ruiken" | "Proeven" | "Voelen"
  imageUrl: string
  website?: string
}

export const culturalInstitutions: CulturalInstitution[] = [
  {
    id: "1",
    name: "Het Scheepvaartmuseum",
    address: "Kattenburgerplein 1, 1018 KK",
    district: "Centrum",
    description: "Ontdek de rijke maritieme geschiedenis van Nederland in het grootste scheepvaartmuseum ter wereld.",
    capacity: 50,
    availableDays: ["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 24 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 50 },
    ],
    sense: "Zien",
    imageUrl: "/maritime-museum-amsterdam.jpg",
    website: "https://www.hetscheepvaartmuseum.nl",
  },
  {
    id: "2",
    name: "Hermitage Amsterdam",
    address: "Amstel 51, 1018 EJ",
    district: "Centrum",
    description: "Ervaar wereldberoemde kunstcollecties uit het Hermitage Museum in Sint-Petersburg.",
    capacity: 30,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "09:00-11:00", capacity: 30 },
      { day: "Woensdag", time: "13:00-15:00", capacity: 30 },
    ],
    sense: "Zien",
    imageUrl: "/hermitage-museum-amsterdam.jpg",
    website: "https://www.hermitage.nl",
  },
  {
    id: "3",
    name: "Imagine IC",
    address: "Eimerstraat 393, 1102 DK Amsterdam",
    district: "Zuidoost",
    description: "Cultureel centrum voor jongeren met workshops, voorstellingen en creatieve activiteiten.",
    capacity: 25,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 25 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Voelen",
    imageUrl: "/imagine-ic-amsterdam.jpg",
    website: "https://www.imagine-ic.nl",
  },
  {
    id: "4",
    name: "JADS",
    address: "Laan 1, 1011 AA",
    district: "Centrum",
    description: "Jeugd- en jongerentheater met interactieve voorstellingen en workshops.",
    capacity: 30,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [{ day: "Woensdag", time: "10:00-12:30", capacity: 30 }],
    sense: "Horen",
    imageUrl: "/youth-theater-amsterdam.jpg",
  },
  {
    id: "5",
    name: "Jeugdtheaterschool Zuidoost",
    address: "Bijlmerdreef 1289, 1103 TV Amsterdam",
    district: "Zuidoost",
    description: "Theaterworkshops en voorstellingen speciaal voor jongeren.",
    capacity: 50,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "09:00-11:00", capacity: 50 },
      { day: "Donderdag", time: "13:00-15:00", capacity: 50 },
    ],
    sense: "Voelen",
    imageUrl: "/youth-theater-school.jpg",
  },
  {
    id: "6",
    name: "Joods Cultureel Kwartier",
    address: "Nieuwe Amstelstraat 1, 1011 PL",
    district: "Centrum",
    description: "Ontdek de Joodse geschiedenis en cultuur van Amsterdam.",
    capacity: 25,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [{ day: "Woensdag", time: "10:00-12:00", capacity: 25 }],
    sense: "Zien",
    imageUrl: "/jewish-cultural-quarter-amsterdam.jpg",
    website: "https://www.jck.nl",
  },
  {
    id: "7",
    name: "Koninklijk Paleis Amsterdam",
    address: "Dam 1",
    district: "Centrum",
    description: "Bezoek het koninklijk paleis en ontdek de rijke geschiedenis van de Nederlandse monarchie.",
    capacity: 60,
    availableDays: ["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "09:00-11:00", capacity: 60 },
      { day: "Woensdag", time: "13:00-15:00", capacity: 60 },
      { day: "Vrijdag", time: "10:00-12:00", capacity: 60 },
    ],
    sense: "Zien",
    imageUrl: "/royal-palace-amsterdam.jpg",
    website: "https://www.paleisamsterdam.nl",
  },
  {
    id: "8",
    name: "Madame Tussauds Amsterdam",
    address: "Dam 20, 1012 NP Amsterdam",
    district: "Centrum",
    description: "Ontmoet levensechte wassenbeelden van beroemdheden en historische figuren.",
    capacity: 20,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [{ day: "Donderdag", time: "13:00-15:00", capacity: 20 }],
    sense: "Zien",
    imageUrl: "/madame-tussauds-amsterdam.jpg",
    website: "https://www.madametussauds.com/amsterdam",
  },
  {
    id: "9",
    name: "Meervaart (Studio)",
    address: "Meer en Vaart 300, 1068 LE Amsterdam",
    district: "West",
    description: "Cultureel centrum met theater, muziek en dans voorstellingen.",
    capacity: 35,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [{ day: "Woensdag", time: "10:00-12:00", capacity: 35 }],
    sense: "Horen",
    imageUrl: "/meervaart-theater-amsterdam.jpg",
    website: "https://www.meervaart.nl",
  },
  {
    id: "10",
    name: "Museum Het Schip",
    address: "Oostzaanstraat 45, 1014 WD Amsterdam",
    district: "West",
    description: "Ontdek de Amsterdamse School architectuur in dit unieke museum.",
    capacity: 50,
    availableDays: ["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "10:00-12:00", capacity: 50 },
      { day: "Dinsdag", time: "14:00-16:00", capacity: 50 },
    ],
    sense: "Zien",
    imageUrl: "/museum-het-schip-amsterdam.jpg",
    website: "https://www.hetschip.nl",
  },
  {
    id: "11",
    name: "Museum Ons' Lieve Heer op Solder",
    address: "Oudezijds Voorburgwal 38, 1012 GE",
    district: "Centrum",
    description: "Verborgen kerkmuseum in het hart van Amsterdam.",
    capacity: 25,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [{ day: "Dinsdag", time: "10:00-12:00", capacity: 25 }],
    sense: "Zien",
    imageUrl: "/museum-ons-lieve-heer-op-solder.jpg",
    website: "https://www.opsolder.nl",
  },
  {
    id: "12",
    name: "Museum Rembrandthuis",
    address: "Jodenbreestraat 4, 1011 NK Amsterdam",
    district: "Centrum",
    description: "Bezoek het voormalige huis en atelier van Rembrandt van Rijn.",
    capacity: 25,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "09:00-11:00", capacity: 25 },
      { day: "Vrijdag", time: "13:00-15:00", capacity: 25 },
    ],
    sense: "Zien",
    imageUrl: "/rembrandt-house-museum-amsterdam.jpg",
    website: "https://www.rembrandthuis.nl",
  },
  {
    id: "13",
    name: "Museum van Loon",
    address: "Keizersgracht 672, 1017 ET Amsterdam",
    district: "Centrum",
    description: "Grachtenhuis museum met authentieke 17e-eeuwse interieurs.",
    capacity: 25,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 25 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Zien",
    imageUrl: "/museum-van-loon-amsterdam.jpg",
    website: "https://www.museumvanloon.nl",
  },
  {
    id: "14",
    name: "Muziekgebouw aan 't IJ",
    address: "Piet Heinkade 1, 1019 BR Amsterdam",
    district: "Oost",
    description: "Modern concertgebouw met diverse muziekstijlen en workshops.",
    capacity: 25,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "10:00-12:00", capacity: 25 },
      { day: "Woensdag", time: "14:00-16:00", capacity: 25 },
      { day: "Vrijdag", time: "10:00-12:00", capacity: 25 },
    ],
    sense: "Horen",
    imageUrl: "/muziekgebouw-aan-t-ij-amsterdam.jpg",
    website: "https://www.muziekgebouw.nl",
  },
  {
    id: "15",
    name: "Muziekschool Amsterdam",
    address: "Marnixstraat 401, 1017 PD Amsterdam",
    district: "Centrum",
    description: "Muziekworkshops en instrumenten uitproberen voor alle niveaus.",
    capacity: 25,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "09:00-11:00", capacity: 25 },
      { day: "Donderdag", time: "13:00-15:00", capacity: 25 },
    ],
    sense: "Horen",
    imageUrl: "/music-school-amsterdam.jpg",
  },
  {
    id: "16",
    name: "Nationale Opera & Ballet",
    address: "Amstel 3, 1011 PN Amsterdam",
    district: "Centrum",
    description: "Ervaar de magie van opera en ballet in het Stopera gebouw.",
    capacity: 25,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [{ day: "Woensdag", time: "10:00-12:00", capacity: 25 }],
    sense: "Horen",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.operaballet.nl",
  },
  {
    id: "17",
    name: "Nederlands Theatermuseum",
    address: "Herengracht 168, 1016 BP Amsterdam",
    district: "Centrum",
    description: "Ontdek de geschiedenis van Nederlands theater en toneel.",
    capacity: 20,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [{ day: "Donderdag", time: "10:00-12:00", capacity: 20 }],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "18",
    name: "NXT Museum",
    address: "Asterweg 22, 1031 HP Amsterdam",
    district: "Noord",
    description: "Museum voor nieuwe media kunst en digitale cultuur.",
    capacity: 100,
    availableDays: ["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 100 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 100 },
      { day: "Vrijdag", time: "10:00-12:00", capacity: 100 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.nxtmuseum.com",
  },
  {
    id: "19",
    name: "Polderhuis",
    address: "Meeuwenlaan 108, 1062 EJ Amsterdam",
    district: "West",
    description: "Cultureel centrum met workshops en exposities.",
    capacity: 25,
    availableDays: ["Maandag", "Woensdag"],
    timeSlots: [{ day: "Woensdag", time: "10:00-12:00", capacity: 25 }],
    sense: "Voelen",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "20",
    name: "Rijksmuseum",
    address: "Museumstraat 1, 1071 XX Amsterdam",
    district: "Centrum",
    description: "Nederlands grootste kunstmuseum met meesterwerken van Rembrandt, Vermeer en Van Gogh.",
    capacity: 60,
    availableDays: ["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "09:00-11:00", capacity: 60 },
      { day: "Dinsdag", time: "13:00-15:00", capacity: 60 },
      { day: "Donderdag", time: "10:00-12:00", capacity: 60 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.rijksmuseum.nl",
  },
  {
    id: "21",
    name: "Sexmuseum Amsterdam",
    address: "Damrak 18, 1012 LH Amsterdam",
    district: "Centrum",
    description: "Museum over de geschiedenis van seksualiteit en erotiek.",
    capacity: 25,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [{ day: "Dinsdag", time: "14:00-16:00", capacity: 25 }],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "22",
    name: "Soundtrackcity Amsterdam",
    address: "Westerdoksdijk 2, 1013 AD Amsterdam",
    district: "Centrum",
    description: "Interactieve audiotour door Amsterdam met verhalen en muziek.",
    capacity: 60,
    availableDays: ["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "09:00-11:00", capacity: 60 },
      { day: "Woensdag", time: "13:00-15:00", capacity: 60 },
      { day: "Vrijdag", time: "10:00-12:00", capacity: 60 },
    ],
    sense: "Horen",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "23",
    name: "Stadsarchief Amsterdam",
    address: "Vijzelstraat 32, 1017 HL Amsterdam",
    district: "Centrum",
    description: "Ontdek de geschiedenis van Amsterdam door archiefstukken en exposities.",
    capacity: 25,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 25 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.amsterdam.nl/stadsarchief",
  },
  {
    id: "24",
    name: "Stedelijk Museum Amsterdam",
    address: "Museumplein 10, 1071 DJ Amsterdam",
    district: "Centrum",
    description: "Museum voor moderne en hedendaagse kunst en design.",
    capacity: 25,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "10:00-12:00", capacity: 25 },
      { day: "Woensdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.stedelijk.nl",
  },
  {
    id: "25",
    name: "STROOM Amsterdam",
    address: "Westerdoksdijk 1, 1013 AD Amsterdam",
    district: "Noord",
    description: "Creatieve werkplaats voor kunst, cultuur en technologie.",
    capacity: 30,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 30 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 30 },
    ],
    sense: "Voelen",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "26",
    name: "Studio Puck van Dijk",
    address: "Wandelweg vanaf Pont",
    district: "Noord",
    description: "Kunstenaarsstudio met workshops en exposities.",
    capacity: 25,
    availableDays: ["Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Woensdag", time: "10:00-12:00", capacity: 25 },
      { day: "Vrijdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Voelen",
    imageUrl: "/placeholder.svg?height=400&width=600",
  },
  {
    id: "27",
    name: "The Amsterdam Dungeon",
    address: "Rokin 78, 1012 KW Amsterdam",
    district: "Centrum",
    description: "Interactieve horror attractie over de duistere geschiedenis van Amsterdam.",
    capacity: 25,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 25 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Voelen",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.thedungeons.com/amsterdam",
  },
  {
    id: "28",
    name: "This is Holland",
    address: "Overhoeksplein 51, 1031 KS Amsterdam",
    district: "Noord",
    description: "5D vliegervaring over Nederland met bewegende stoelen en effecten.",
    capacity: 50,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "10:00-12:00", capacity: 50 },
      { day: "Woensdag", time: "14:00-16:00", capacity: 50 },
      { day: "Vrijdag", time: "10:00-12:00", capacity: 50 },
    ],
    sense: "Voelen",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.thisisholland.com",
  },
  {
    id: "29",
    name: "Van Gogh Museum",
    address: "Museumplein 6, 1071 DJ Amsterdam",
    district: "Centrum",
    description: "Grootste collectie kunstwerken van Vincent van Gogh ter wereld.",
    capacity: 25,
    availableDays: ["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "09:00-11:00", capacity: 25 },
      { day: "Woensdag", time: "13:00-15:00", capacity: 25 },
      { day: "Vrijdag", time: "10:00-12:00", capacity: 25 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.vangoghmuseum.nl",
  },
  {
    id: "30",
    name: "Verzetsmuseum Amsterdam",
    address: "Plantage Kerklaan 61, 1018 CX Amsterdam",
    district: "Centrum",
    description: "Museum over het Nederlandse verzet tijdens de Tweede Wereldoorlog.",
    capacity: 25,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 25 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.verzetsmuseum.org",
  },
  {
    id: "31",
    name: "Westergas Amsterdam",
    address: "Klönneplein 1, 1014 DD Amsterdam",
    district: "West",
    description: "Cultureel park met evenementen, festivals en workshops.",
    capacity: 25,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Woensdag", time: "10:00-12:00", capacity: 25 },
      { day: "Vrijdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Voelen",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.westergas.nl",
  },
  {
    id: "32",
    name: "WONDR Experience",
    address: "Meeuwenlaan 88, 1021 JK Amsterdam",
    district: "Noord",
    description: "Interactieve kunst- en speelervaring met Instagram-waardige installaties.",
    capacity: 25,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 25 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.wondrexperience.com",
  },
  {
    id: "33",
    name: "EYE Filmmuseum",
    address: "IJpromenade 1, 1031 KT Amsterdam",
    district: "Noord",
    description: "Filmmuseum met exposities, filmvertoningen en interactieve installaties.",
    capacity: 50,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "10:00-12:00", capacity: 50 },
      { day: "Woensdag", time: "14:00-16:00", capacity: 50 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.eyefilm.nl",
  },
  {
    id: "34",
    name: "Body Worlds",
    address: "Damrak",
    district: "Centrum",
    description: "Anatomische tentoonstelling met echte menselijke lichamen.",
    capacity: 30,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 30 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 30 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.bodyworlds.nl",
  },
  {
    id: "35",
    name: "NEMO Science Museum",
    address: "Oosterdok 2, 1011 VX Amsterdam",
    district: "Centrum",
    description: "Grootste science center van Nederland met hands-on experimenten.",
    capacity: 60,
    availableDays: ["Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "09:00-11:00", capacity: 60 },
      { day: "Dinsdag", time: "13:00-15:00", capacity: 60 },
      { day: "Donderdag", time: "10:00-12:00", capacity: 60 },
    ],
    sense: "Voelen",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.nemosciencemuseum.nl",
  },
  {
    id: "36",
    name: "Anne Frank Huis",
    address: "Prinsengracht 263-267, 1016 GV Amsterdam",
    district: "Centrum",
    description: "Museum gewijd aan de Joods-Duitse dagboekschrijfster Anne Frank.",
    capacity: 25,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "10:00-12:00", capacity: 25 },
      { day: "Woensdag", time: "14:00-16:00", capacity: 25 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.annefrank.org",
  },
  {
    id: "37",
    name: "Micropia",
    address: "Plantage Kerklaan 38-40, 1018 CZ Amsterdam",
    district: "Centrum",
    description: "Eerste microbenmuseum ter wereld met levende micro-organismen.",
    capacity: 30,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 30 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 30 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.micropia.nl",
  },
  {
    id: "38",
    name: "Artis Zoo",
    address: "Plantage Kerklaan 38-40, 1018 CZ Amsterdam",
    district: "Centrum",
    description: "Oudste dierentuin van Nederland met meer dan 900 diersoorten.",
    capacity: 50,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [
      { day: "Maandag", time: "09:00-11:00", capacity: 50 },
      { day: "Woensdag", time: "13:00-15:00", capacity: 50 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.artis.nl",
  },
  {
    id: "39",
    name: "Tropenmuseum",
    address: "Linnaeusstraat 2, 1092 CK Amsterdam",
    district: "Oost",
    description: "Museum over wereldculturen met collecties uit Afrika, Azië en Latijns-Amerika.",
    capacity: 40,
    availableDays: ["Dinsdag", "Donderdag"],
    timeSlots: [
      { day: "Dinsdag", time: "10:00-12:00", capacity: 40 },
      { day: "Donderdag", time: "14:00-16:00", capacity: 40 },
    ],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.tropenmuseum.nl",
  },
  {
    id: "40",
    name: "Foam Fotografiemuseum",
    address: "Keizersgracht 609, 1017 DS Amsterdam",
    district: "Centrum",
    description: "Museum voor hedendaagse fotografie met wisselende exposities.",
    capacity: 25,
    availableDays: ["Maandag", "Woensdag", "Vrijdag"],
    timeSlots: [{ day: "Woensdag", time: "10:00-12:00", capacity: 25 }],
    sense: "Zien",
    imageUrl: "/placeholder.svg?height=400&width=600",
    website: "https://www.foam.org",
  },
]

export const partnerOrganizations = [
  {
    name: "ROC van Amsterdam",
    website: "https://www.rocva.nl",
    logo: "/placeholder.svg?height=80&width=200",
  },
  {
    name: "Mediacollege Amsterdam",
    website: "https://www.ma-web.nl",
    logo: "/placeholder.svg?height=80&width=200",
  },
  {
    name: "Hout en Meubileringscollege Amsterdam",
    website: "https://www.hmc.nl",
    logo: "/placeholder.svg?height=80&width=200",
  },
  {
    name: "Amsterdams Platform Cultuureducatie MBO",
    website: "https://www.cultuureducatie.nl",
    logo: "/placeholder.svg?height=80&width=200",
  },
  {
    name: "Stichting Museumnacht Amsterdam",
    website: "https://www.n8.nl",
    logo: "/placeholder.svg?height=80&width=200",
  },
  {
    name: "Museum Vereniging",
    website: "https://www.museumvereniging.nl",
    logo: "/placeholder.svg?height=80&width=200",
  },
  {
    name: "GVB",
    website: "https://www.gvb.nl",
    logo: "/placeholder.svg?height=80&width=200",
  },
  {
    name: "MOCCA Expertisecentrum Cultuuronderwijs",
    website: "https://www.mocca-amsterdam.nl",
    logo: "/placeholder.svg?height=80&width=200",
  },
  {
    name: "CJP",
    website: "https://www.cjp.nl",
    logo: "/placeholder.svg?height=80&width=200",
  },
]
